# File: .github/workflows/repo-sync.yml
name: 同步U188-PJJ上游仓库
on:
  schedule:
    - cron: '0 9 */3 * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-repo
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync U188/PJJ
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/U188/PJJ.git"
          source_branch: "main"
          destination_branch: "U188_PJJ"
          github_token: ${{ secrets.PAT }}

      - name: sync panghu999/jc88
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/panghu999/jc88.git"
          source_branch: "main"
          destination_branch: "U188_P88"
          github_token: ${{ secrets.PAT }}
