# File: .github/workflows/repo-sync.yml
name: smiek2221_scripts  #workflows处显示名称
on:
  schedule:
    - cron: '20 */8 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-repo
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync smiek2221/scripts  #类似注释
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/smiek2221/scripts.git"
          source_branch: "master"
          destination_branch: "smiek2221"
          github_token: ${{ secrets.PAT }}
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
